Allow adding unique userdata to instances
itay-grudev/SingleApplication pull request #122
Opened 2020-12-11 00:39 UTC by LorenDB

I did this because I'm contributing to an app that uses user profiles and needs to have only one instance of each profile.

By the way, I tried to follow the coding style used in SingleApplication.

2020-12-13 11:16 UTC, itay-grudev commented
What is the use case for this?

2020-12-13 13:39 UTC, LorenDB commented
I'm working on github.com/Nheko-reborn/nheko. I was trying to add profiles to nheko, but I wanted a way to only block windows from opening if there was already a window open with the profile that the user was trying to load. So in my case, I can have the default profile in one window running the latest stable release, the same account in another profile "git" in a window built on the latest code,  but when I try opening another window with the git profile, it raises the first git window.

2020-12-13 13:43 UTC, itay-grudev commented
But your code adds the ability to set it on a instance but doesn't share it in in any way with the rest of the instances. To achieve your goal you would need to save this in the shared memory.

2020-12-14 12:46 UTC, LorenDB commented
> But your code adds the ability to set it on a instance but doesn't share it in in any way with the rest of the instances. To achieve your goal you would need to save this in the shared memory.

I'm not sure what you're getting at.

Basically, I'm using the userdata to add to the data that is used to generate the key for the QSharedMemory. In my opinion, that should be all that is necessary.

2020-12-14 12:49 UTC, itay-grudev commented
@LorenDB You are correct. I missed on line when I was doing the review last night.

2020-12-14 12:50 UTC, itay-grudev requested changes
Would you also be kind enough to add some documentation in the README?

2020-12-14 12:51 UTC, LorenDB commented on singleapplication.cpp
> +SingleApplication::SingleApplication( int &argc, char *argv[], bool allowSecondary, Options options, QString userData, int timeout )
Sure

2020-12-14 13:00 UTC, LorenDB commented
Just pushed changes. I did remove the setAppData function from SingleApplication because there's not really any way set up to modify the QSharedMemory key after new user data is set. I also made the naming agree (it's now user data everywhere).

2020-12-14 13:04 UTC, itay-grudev commented
Ok. I like it.
@jonaski Do you mind reviewing it as well?

2020-12-14 13:05 UTC, itay-grudev approved these changes

2020-12-14 13:07 UTC, itay-grudev commented
There is a false positive test failure in the Qt 6 build specs, but this is not related. I think it's a bug elsewhere because the tests started failing without the code having been changed.

2020-12-17 03:10 UTC, jonaski commented on singleapplication.cpp
> +    if ( ! userData.isNull() )
Shouldn't this be isEmpty instead?

2020-12-17 03:10 UTC, jonaski commented on singleapplication.h
> +    explicit SingleApplication( int &argc, char *argv[], bool allowSecondary = false, Options options = Mode::User, int timeout = 1000, QString userData = "" );
QString() instead of ""?

2020-12-17 03:11 UTC, jonaski commented
@itay-grudev I added 2 comments, let me know if you agree.

2020-12-17 03:12 UTC, LorenDB commented on singleapplication.cpp
> +    if ( ! userData.isNull() )
Hmm, you're right.

2020-12-17 03:15 UTC, LorenDB commented
> @itay-grudev I added 2 comments, let me know if you agree.

I just updated to use those changes, I think they are both valid.

2020-12-17 03:16 UTC, jonaski commented on README.md
> +SingleApplication::SingleApplication( int &argc, char *argv[], bool allowSecondary = false, Options options = Mode::User, int timeout = 100, QString userData = "" )
QString() here to match the constructor

2020-12-17 03:17 UTC, LorenDB commented on README.md
> +SingleApplication::SingleApplication( int &argc, char *argv[], bool allowSecondary = false, Options options = Mode::User, int timeout = 100, QString userData = "" )
Done

2020-12-17 03:18 UTC, jonaski approved these changes

2020-12-17 09:47 UTC, merged

2020-12-17 09:48 UTC, itay-grudev commented
Thank you @LorenDB. I'll add a changelog entry and credit you as Loren Burkholder, with your permission.

2020-12-17 13:05 UTC, LorenDB commented
Go right ahead!