Remove ConnectionInfo after socket is destroyed
itay-grudev/SingleApplication pull request #125
Opened 2020-12-23 02:05 UTC by dail8859

As described in https://github.com/itay-grudev/SingleApplication/issues/121#issuecomment-734225947 the socket can still emit a `readyRead()` after `disconnect()` is emitted. This can be seen by adding a bit of debug code to the `disconnect()` signal and also in the `readyRead()` to verify the `ConnectionInfo` is missing. This would cause a new struct to be created, and think that the connection is still at the "Header" stage, which would eat the first 8 bytes of a message being sent.

Instead of removing the `ConnectionInfo` when the socket is disconnected, wait till it is actually destroyed. These changes are far simpler than I had made originally :)

This PR closes #123.

2020-12-23 15:50 UTC, Shatur95 requested changes
Thanks for the PR.

But do we need to wait for the complete deletion of the object?
Could you try to call `disconnect(nextConnSocket, &QLocalSocket::readyRead, nullptr, nullptr);` in the lambda that was before your PR?

2020-12-23 15:50 UTC, Shatur95 commented on singleapplication_p.cpp
> +            Q_UNUSED(obj)
In Qt, you don't need a slot to have the same number of arguments as a signal. So, you can just omit `QObject *`.

```suggestion
        [nextConnSocket, this](){
```

2020-12-23 20:42 UTC, dail8859 commented on singleapplication_p.cpp
> +            Q_UNUSED(obj)
Did not know that! Thanks!

2020-12-23 20:43 UTC, dail8859 commented
> But do we need to wait for the complete deletion of the object?

I believe so because even after the socket is disconnected it is still triggering (probably one final) `readyRead()` with a valid `QLocalSocket` object. Once it is deleted the socket could no longer emit any signals.

> Could you try to call disconnect (nextConnSocket, &QLocalSocket :: destroyed, nullptr, nullptr); in the lambda that was before your PR?

I'm not sure I understand the need for this. I'm probably missing something obvious. I'm by no means a Qt expert. :)

2020-12-23 21:22 UTC, Shatur95 commented
> I'm not sure I understand the need for this. I'm probably missing something obvious. I'm by no means a Qt expert. :)

Not a problem, could you just try the following patch? [patch.zip](https://github.com/itay-grudev/SingleApplication/files/5737165/patch.zip)

Download, unpack, switch to `master` branch and use `git apply <path to unpacked patch>`.

2020-12-23 21:49 UTC, dail8859 commented
Ah, thanks for that.

In my testing I've seen that the `readyRead()` signal can still come _after_ the disconnect so if you disconnected then you would never possibly receive some data.

On the `master` branch, apply this patch and run the `send_arguments` example. It adds some debugging, and also some artificial delay to cause the bug. [debug.zip](https://github.com/itay-grudev/SingleApplication/files/5737240/debug.zip)

I get debug output like this:
![image](https://user-images.githubusercontent.com/3694843/103039106-076ffa00-453e-11eb-85c2-62fa0589dafe.png)

After it disconnects it is missing the `ConnectionInfo` and loses the first 8 bytes `C:\Users` in this case.

That's why the `ConnectionInfo` can only be removed from the map once the socket is truly destroyed.

2020-12-23 23:06 UTC, Shatur95 approved these changes
Thanks for checking!
The code and the approach looks good to me.

@nioncode, could you also check it?

2020-12-24 21:55 UTC, nioncode commented
This at least solves parts of the problem of #121 (namely that the `ConnectionInfo` is removed too early from the `connectionMap`).

It still happens that not the entire `instanceStarted` message gets received (but only the initial 8 bytes header), which might be caused by the sender closing the the connection too early, before everything has been flushed, so #121 is not completely solved with this PR.

It certainly a step in the right direction and fixes the problem of @dail8859, so LGTM.

2020-12-24 23:30 UTC, Shatur95 commented
@nioncode, thanks!
@itay-grudev, @jonaski, guys need your approval to merge this.

2020-12-25 08:56 UTC, itay-grudev approved these changes

2020-12-25 08:56 UTC, merged

2020-12-25 12:42 UTC, dail8859 commented
Thanks all for the review and help!