provide API for blocking sendMessage
itay-grudev/SingleApplication pull request #154
Opened 2022-04-04 16:35 UTC by christoph-cullmann

useful if the secondary instances should wait until the primary exits

use e.g. in Kate for the kate -b xyz blocking behavior

As promised in the other pull request, here my additional api for blocking send, cleaned up a bit with an extra enum.

2022-04-04 16:53 UTC, Shatur requested changes
Thanks! Here is some minor suggestions

2022-04-04 16:53 UTC, Shatur commented on singleapplication.h
> +    Q_DECLARE_FLAGS(SendOptions, SendMode)
I don't think we will have more options, so I would turn it into a simple enum:
```suggestion
    enum SendMode {
        Blocking,  /** Wait until the primary instance is terminated */
        NonBlocking,  /** Do not wait for the primary instance termination and return immediately */
    };
```

2022-04-04 16:53 UTC, Shatur commented on singleapplication_p.cpp
> +    // block if needed
```suggestion
    // Block if needed
```

2022-04-04 20:18 UTC, itay-grudev requested changes

2022-04-04 20:18 UTC, itay-grudev commented on singleapplication.h
> +    Q_DECLARE_FLAGS(SendOptions, SendMode)
I recommend the `NonBlocking` default goes first so it's code is zero.
```suggestion
    enum SendMode {
        NonBlocking,  /** Do not wait for the primary instance termination and return immediately */
        Blocking,  /** Wait until the primary instance is terminated */
    };
```

2022-04-04 20:20 UTC, Shatur commented
@itay-grudev agree!

2022-04-04 20:20 UTC, Shatur commented on singleapplication.h
> +    Q_DECLARE_FLAGS(SendOptions, SendMode)
Agree!

2022-04-04 20:21 UTC, itay-grudev commented
@Shatur @christoph-cullmann Maybe we should even call it: `BlockUntilExit` or `BlockUntilPrimaryExit` just to make it very clear that this not just a request-response block.

2022-04-04 20:23 UTC, Shatur commented
> BlockUntilPrimaryExit

I like it!

2022-04-05 18:17 UTC, christoph-cullmann commented
Will cleanup the patch, good input, true, not likely one will have really more then one flag here, just wanted to make it similar to the other flags stuff.

Not familiar with GitHub work flow here, just commited the stuff that made sense via the web interface and will check later locally the results.

I assume one can later just merge this squashed into one commit.

2022-04-05 18:34 UTC, Shatur requested changes
Thanks!
Last minor style suggestions, you can confirm it from browser.
May I also ask you to update `CHANGELOG.md` too?

2022-04-05 18:34 UTC, Shatur commented on singleapplication.cpp
> + * @param block block until the primary application exits
Probably forgot to update the description?
```suggestion
 * @param sendMode mode of operation
```

2022-04-05 18:34 UTC, Shatur commented on singleapplication.h
> +        NonBlocking,            /** Do not wait for the primary instance termination and return immediately */
We usually do not alight such things:
```suggestion
        NonBlocking,  /** Do not wait for the primary instance termination and return immediately */
```

2022-04-05 18:34 UTC, Shatur commented on singleapplication_p.cpp
> +    if (socket && (sendMode == SingleApplication::BlockUntilPrimaryExit))
We usually omit extra brackets:
```suggestion
    if (socket && sendMode == SingleApplication::BlockUntilPrimaryExit)
```

2022-04-05 18:41 UTC, christoph-cullmann commented on singleapplication.h
> +        NonBlocking,            /** Do not wait for the primary instance termination and return immediately */
Ok, sure, no problem with that, just thought as you aligned the asignments in the other mode flags enum that would match better.

2022-04-05 18:58 UTC, itay-grudev approved these changes

2022-04-05 20:46 UTC, Shatur approved these changes
Let's merge it as is, I will update `CHANGELOG.md` myself.

2022-04-05 20:46 UTC, merged