Windows raise widget example
itay-grudev/SingleApplication pull request #167
Opened 2023-03-13 09:13 UTC by samsonwang

Bring widget to the front when second instance is started, this is a workaround for Windows system.

2023-03-13 09:23 UTC, samsonwang commented
The second instance should call `AllowSetForegroundWindow` before the first instance calls `SetForegoundWindow`.
The `instanceStared` signal is emitted once the second instance is created.
So, the second instance have to use `sendMessage` to notify the first instance.

2023-03-13 10:21 UTC, Shatur requested changes
Thanks!

2023-03-13 10:21 UTC, Shatur commented on examples/windows_raise_widget/main.cpp
> +void RaiseWidget(QWidget* widget) {
We use camelCase for function names in this project. Could you rename it into `raiseWidget`?

2023-03-13 10:21 UTC, Shatur commented on Windows.md
> +Here is an example, you can find this code in the example directory:
Instead of copying code I would just add link to the example.

2023-03-14 07:58 UTC, Shatur commented on Windows.md
> +You can find demo code in the [examples](examples/windows_raise_widget/main.cpp) directory.
One minor nitpick and we are good to go:
```suggestion
You can find [demo code](examples/windows_raise_widget/main.cpp) in the examples directory.
```

2023-03-14 10:57 UTC, samsonwang commented on Windows.md
> +You can find demo code in the [examples](examples/windows_raise_widget/main.cpp) directory.
It looks better.

2023-03-15 16:50 UTC, itay-grudev commented
Looks good to me. @Shatur I think you need to approve the changes you requested.

2023-03-15 17:51 UTC, Shatur approved these changes

2023-03-16 13:18 UTC, merged